server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodappdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connectionTimeout: 30000
    maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
